DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) DEFAULT 'https://toppng.com/uploads/preview/egg-png-11553982261qbkbn5fjgy.png'
);
CREATE TABLE books (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  item TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  is_completed BOOLEAN DEFAULT TRUE
);
CREATE TABLE movies (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  item TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  is_completed BOOLEAN DEFAULT TRUE
);
CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  item TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  is_completed BOOLEAN DEFAULT TRUE
);
CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  item TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  is_completed BOOLEAN DEFAULT TRUE
);
